apiVersion: v1
kind: Service
metadata:
  name: backend-svc
spec:
  type: LoadBalancer        # ðŸ‘ˆ ESTO es lo clave
  selector:
    app: backend            # ðŸ‘ˆ debe coincidir con los labels del Deployment del backend
  ports:
    - name: http
      port: 8000            # puerto expuesto en el LB
      targetPort: 8000      # puerto donde escucha Django en el pod
      protocol: TCP
